version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: lenslocked
    volumes:
      - ./sql/users.sql:/docker-entrypoint-initdb.d/users.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
     ADMINER_DESIGN: dracula